source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.baijiashilian.com/open-ios/specs.git'

platform :ios, '9.0'

target 'BJLiveUISwiftDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for BJLiveUISwiftDemo
    
    # #see http://guides.cocoapods.org/syntax/podfile.html#script_phase
    script_phase :name => '[BJLiveCore] Embed Frameworks',
    :script => 'Pods/BJLiveCore/frameworks/EmbedFrameworks.sh', # for remote pod
    :execution_position => :after_compile
    
    # #see https://stackoverflow.com/a/30866648/456536
    script_phase \
    :name => '[BJLiveBase] Clear Archs From Frameworks',
    :script => 'Pods/BJLiveBase/script/ClearArchsFromFrameworks.sh "BJHLMediaPlayer.framework"', # for remote pod
    :execution_position => :after_compile
    
    # dev
    pod 'BJLiveUI', :path => '../'

    # demo
    pod 'Masonry', :inhibit_warnings => true
    pod 'ReactiveObjC', :inhibit_warnings => true
    
    target 'BJLiveUISwiftDemoTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'BJLiveUISwiftDemoUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
