source 'https://github.com/CocoaPods/Specs.git'
source 'http://git.baijiashilian.com/open-ios/specs.git'

platform :ios, '9.0'
# inhibit_all_warnings!

# fix warning: [!] [Xcodeproj] Generated duplicate UUIDs:
# @see http://stackoverflow.com/a/33440077/456536
# !!!: local projects with soft link will generate this warning
# install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
    
    installer.pods_project.root_object.attributes["CLASSPREFIX"] = "BJL"
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "BaijiaYun"
    
    ## IPHONEOS_DEPLOYMENT_TARGET
    # @see https://stackoverflow.com/a/37289688/456536
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
    
end

target 'BJLiveUI' do
    
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # #see http://guides.cocoapods.org/syntax/podfile.html#script_phase
    script_phase :name => '[BJLiveCore] Embed Frameworks',
    :script => 'Pods/BJLiveCore/frameworks/EmbedFrameworks.sh', # for remote pod
    :execution_position => :after_compile
    
    # #see https://stackoverflow.com/a/30866648/456536
    script_phase \
    :name => '[BJLiveBase] Clear Archs From Frameworks',
    :script => 'Pods/BJLiveBase/script/ClearArchsFromFrameworks.sh "BJHLMediaPlayer.framework"', # for remote pod
    :execution_position => :after_compile
    
    # dev
    pod 'BJLiveUI', :path => '../'

    # demo
    pod 'Masonry', :inhibit_warnings => true
    pod 'ReactiveObjC', :inhibit_warnings => true
    
    # debug
    pod 'FLEX', '~> 2.0', :configurations => ['Debug'], :inhibit_warnings => true
    
    target 'BJLiveUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'BJLiveUIUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
end
